[holla]add: 카카오 소셜 로그인 구현
wecode-bootcamp-korea/26-2nd-Holla-backend pull request #4
Opened 2021-11-18 08:43 UTC by solarrrrr1010

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 로그인 api를 이용한 소셜 로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 프론트로부터 유효한 액세스 토큰을 헤더로 받아 카카오 서버와 통신을 통해 
토큰의 사용자 정보를 받아옵니다.
받아온 사용자 정보와 서버 db의 데이터를 get or create 구문으로 비교하여 
사용자가 있다면 바로 jwt encode로 토큰을 생성해 반환하고 
사용자가 없다면 db에 사용자 정보를 넣은 후 토큰을 생성해 프론트로 반환합니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 카카오 로그인 api의 전체적인 flow를 알 수 있었고 사용 방법을 알았습니다.
- get or create 사용 방법을 익혔습니다. 간결한 코드 작성에 유용한 것 같습니다.

<br />

## :: 기타 질문 및 특이 사항
- 카카오로부터 받는 액세스 토큰의 사용자 정보가 비어 있는 문제의 해결이 안 돼 궁금합니다.
- 카카오 싱크를 통해 뭔가를 해야 한다고 하는데 시간 날 때 해결해 보겠습니다.

2021-11-18 14:02 UTC, jamessoun93 requested changes
첫 소셜로그인 기능 구현 정말 잘하셨습니다!
리뷰 남겨드렸으니 확인해주세요 👍

2021-11-18 14:02 UTC, jamessoun93 commented on users/urls.py
> +    path('/kakao_signin', KakaoSignInView.as_view()),
여기서는 uri 를 정하실때 언더바 `_` 로 구분하시는 것 보다 `/` 로 구분하시는게 더 좋아보이네요!
```suggestion
    path('/kakao/signin', KakaoSignInView.as_view()),
```

2021-11-18 14:02 UTC, jamessoun93 commented on users/views.py
> +            access_token   = request.headers.get('Authorization', None)
Authorization headers 값이 존재하지 않는 경우에 대한 에러처리를 추가해주세요.

2021-11-18 14:02 UTC, jamessoun93 commented on users/views.py
> +                settings.SECRET_KEY, algorithm = settings.ALGORITHM)
이 부분은 `\` 로 줄바꿈을 하니 오히려 가독성이 떨어지는 것 같습니다. 
jwt 의 payload 부분을 위에서 변수에 담아놓은뒤 한줄로 작성해도 좋을 것 같네요.
```python
jwt_payload = {'id': obj.id}

access_token = jwt.encode(jwt_payload, settings.SECRET_KEY, algorithm = settings.ALGORITHM)
```

2021-11-18 14:02 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'message' : 'SUCCESS', 'ACCESS_TOKEN': access_token}, status=200)
json body 의 key 값을 소문자로 통일해주세요.
```suggestion
            return JsonResponse({'message' : 'SUCCESS', 'access_token': access_token}, status=200)
```

2021-11-19 00:44 UTC, solarrrrr1010 commented on users/urls.py
> +    path('/kakao_signin', KakaoSignInView.as_view()),
넵 수정했습니다!

2021-11-19 00:45 UTC, solarrrrr1010 commented on users/views.py
> +            access_token   = request.headers.get('Authorization', None)
이 경우 터미널에 Attribute error가 뜨던데 except에 Attribute error로 잡아주면 될까요? 혹은 전달 메시지에 nonetype에 대한 오류로 정확히 명시해 주는 게 좋을까요?

2021-11-19 00:46 UTC, solarrrrr1010 commented on users/views.py
> +                settings.SECRET_KEY, algorithm = settings.ALGORITHM)
감사합니다. 적용하겠습니다!

2021-11-19 00:46 UTC, solarrrrr1010 commented on users/views.py
> +            return JsonResponse({'message' : 'SUCCESS', 'ACCESS_TOKEN': access_token}, status=200)
죄송합니다. 좀더 꼼꼼히 확인하겠습니다!

2021-11-19 08:08 UTC, jamessoun93 requested changes

2021-11-19 08:08 UTC, jamessoun93 commented on users/views.py
> +            access_token   = request.headers.get("Authorization", None)
```suggestion
            access_token   = request.headers["Authorization"]
```
KeyError 발생

2021-11-19 08:08 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({"message" : "SUCCESS", "access_token": access_token}, status=200)
created 조건에 따른 status code 변경

2021-11-19 08:08 UTC, jamessoun93 commented on users/views.py
> +          return JsonResponse({"message" : "KEY_ERROR"}, status=401)
메세지 조금 더 상세하게 수정

2021-11-19 08:08 UTC, jamessoun93 commented on users/views.py
> +            nickname       = kakao_response.json().get("properties").get("nickname")
```suggestion
            kakao_id       = kakao_response.json()["id"]
            email          = kakao_response.json()["kakao_account"]["email"]
            nickname       = kakao_response.json()["properties"]["nickname"]
```

2021-11-20 06:35 UTC, jamessoun93 commented
충돌해결해주세요!

2021-11-20 07:25 UTC, jamessoun93 approved these changes, later dismissed
LGTM 👍

2021-11-20 14:11 UTC, jamessoun93 approved these changes
LGTM 🚀

2021-11-20 14:11 UTC, merged